FROM {{ image_spec("openstack-base") }}
MAINTAINER {{ maintainer }}

{{ copy_sources("openstack/searchlight", "/searchlight") }}

RUN useradd --user-group -G microservices searchlight \
    && /var/lib/microservices/venv/bin/pip install --upgrade /searchlight \
    && mkdir -p /var/lib/searchlight /etc/searchlight \
    && cp -r /searchlight/etc/* /etc/searchlight/ \
    && chown -R searchlight:searchlight /etc/searchlight /var/lib/searchlight \
    && rm -r /searchlight
